# Create global workflow output equivalents to all of the Classic Codefresh git pipeline
# variables, documented here: https://codefresh.io/docs/docs/codefresh-yaml/variables
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: codefresh.github
  labels:
    owner: codefresh
spec:
  templates:
    - name: get-github-info
      inputs:
        parameters:
        - name: GITHUB_JSON  # JSON string with the event payload from GitHub
      container:
        image: gtspinks/githubinfo:latest
        command: ["python3"]
        args: ["/parse_github_payload.py"]
        env:
        - name: GITHUB_JSON
          value: '{{ inputs.parameters.GITHUB_JSON }}'
      outputs:
        parameters:
        - name: CF_REPO_OWNER
          valueFrom:
            path: /tmp/gitvars/CF_REPO_OWNER
          globalName: CF_REPO_OWNER
        - name: CF_REPO_NAME
          valueFrom:
            path: /tmp/gitvars/CF_REPO_NAME
          globalName: CF_REPO_NAME
        - name: CF_BRANCH
          valueFrom:
            path: /tmp/gitvars/CF_BRANCH
          globalName: CF_BRANCH
        - name: CF_BASE_BRANCH
          valueFrom:
            path: /tmp/gitvars/CF_BASE_BRANCH
          globalName: CF_BASE_BRANCH
        - name: CF_COMMIT_AUTHOR
          valueFrom:
            path: /tmp/gitvars/CF_COMMIT_AUTHOR
          globalName: CF_COMMIT_AUTHOR
        - name: CF_COMMIT_USERNAME
          valueFrom:
            path: /tmp/gitvars/CF_COMMIT_USERNAME
          globalName: CF_COMMIT_USERNAME
        - name: CF_COMMIT_EMAIL
          valueFrom:
            path: /tmp/gitvars/CF_COMMIT_EMAIL
          globalName: CF_COMMIT_EMAIL
        - name: CF_COMMIT_URL
          valueFrom:
            path: /tmp/gitvars/CF_COMMIT_URL
          globalName: CF_COMMIT_URL
        - name: CF_COMMIT_MESSAGE
          valueFrom:
            path: /tmp/gitvars/CF_COMMIT_MESSAGE
          globalName: CF_COMMIT_MESSAGE
        - name: CF_REVISION
          valueFrom:
            path: /tmp/gitvars/CF_REVISION
          globalName: CF_REVISION
        - name: CF_SHORT_REVISION
          valueFrom:
            path: /tmp/gitvars/CF_SHORT_REVISION
          globalName: CF_SHORT_REVISION
        - name: CF_PULL_REQUEST_ACTION
          valueFrom:
            path: /tmp/gitvars/CF_PULL_REQUEST_ACTION
          globalName: CF_PULL_REQUEST_ACTION
        - name: CF_PULL_REQUEST_TARGET
          valueFrom:
            path: /tmp/gitvars/CF_PULL_REQUEST_TARGET
          globalName: CF_PULL_REQUEST_TARGET
        - name: CF_PULL_REQUEST_NUMBER
          valueFrom:
            path: /tmp/gitvars/CF_PULL_REQUEST_NUMBER
          globalName: CF_PULL_REQUEST_NUMBER
        - name: CF_PULL_REQUEST_ID
          valueFrom:
            path: /tmp/gitvars/CF_PULL_REQUEST_ID
          globalName: CF_PULL_REQUEST_ID
        - name: CF_PULL_REQUEST_LABELS
          valueFrom:
            path: /tmp/gitvars/CF_PULL_REQUEST_LABELS
          globalName: CF_PULL_REQUEST_LABELS
        - name: CF_RELEASE_NAME
          valueFrom:
            path: /tmp/gitvars/CF_RELEASE_NAME
          globalName: CF_RELEASE_NAME
        - name: CF_RELEASE_TAG
          valueFrom:
            path: /tmp/gitvars/CF_RELEASE_TAG
          globalName: CF_RELEASE_TAG
        - name: CF_RELEASE_ID
          valueFrom:
            path: /tmp/gitvars/CF_RELEASE_ID
          globalName: CF_RELEASE_ID
        - name: CF_PRERELEASE_FLAG
          valueFrom:
            path: /tmp/gitvars/CF_PRERELEASE_FLAG
          globalName: CF_PRERELEASE_FLAG
        - name: CF_PULL_REQUEST_MERGED
          valueFrom:
            path: /tmp/gitvars/CF_PULL_REQUEST_MERGED
          globalName: CF_PULL_REQUEST_MERGED
        - name: CF_PULL_REQUEST_HEAD_BRANCH
          valueFrom:
            path: /tmp/gitvars/CF_PULL_REQUEST_HEAD_BRANCH
          globalName: CF_PULL_REQUEST_HEAD_BRANCH
        - name: CF_PULL_REQUEST_MERGED_COMMIT_SHA
          valueFrom:
            path: /tmp/gitvars/CF_PULL_REQUEST_MERGED_COMMIT_SHA
          globalName: CF_PULL_REQUEST_MERGED_COMMIT_SHA
        - name: CF_PULL_REQUEST_HEAD_COMMIT_SHA
          valueFrom:
            path: /tmp/gitvars/CF_PULL_REQUEST_HEAD_COMMIT_SHA
          globalName: CF_PULL_REQUEST_HEAD_COMMIT_SHA
