apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: clone-and-build
  labels:
    git-branch: dynamic
    git-revision: dynamic
    workflow-template-name: argo-platform-ci
spec:
  arguments:
    parameters:
      - name: GIT_REPO
      - name: GIT_REVISION
      - name: GIT_BRANCH
      - name: GIT_REPO_OWNER
      - name: GIT_REPO_NAME
      - name: GIT_COMMIT_MESSAGE
      - name: GIT_COMMIT_URL
  entrypoint: ci-pipeline
  onExit: exit-handler
  imagePullSecrets:
    - name: docker-registry
  volumes:
    - name: docker-config
      secret:
        items:
          - key: .dockerconfigjson
            path: config.json
        secretName: docker-registry
    # - name: gcr-key-file
    #   secret:
    #     items:
    #       - key: .keyjson
    #         path: key.json
    #     secretName: gcr-key-file
  templates:
    - name: ci-pipeline
      dag:
        tasks:
          # - name: report-commit-status-start
          #   templateRef:
          #     name: codefresh.github-commit-status
          #     template: main
          #   arguments:
          #     parameters:
          #       - name: BUILD_BASE_URL
          #         value: >-
          #           https://inc03.cf-op.com/workflows/workflows/codefresh-v2-production/
          #       - name: REPO_OWNER
          #         value: codefresh-io
          #       - name: REPO_NAME
          #         value: argo-platform
          #       - name: REVISION
          #         value: '{{ workflow.parameters.GIT_REVISION }}'
          #       - name: STATE
          #         value: pending
          #       - name: CONTEXT
          #         value: argo-platform/ci
          #       - name: DESCRIPTION
          #         value: Workflow is running
          #       - name: GITHUB_TOKEN_SECRET
          #         value: github-token
          # - name: is-no-change-mode
          #   templateRef:
          #     name: common-util
          #     template: is-no-change-mode
          #   arguments:
          #     parameters:
          #       - name: REPO_OWNER
          #         value: codefresh-io
          #       - name: REPO_NAME
          #         value: argo-platform
          #       - name: BRANCH
          #         value: '{{ workflow.parameters.GIT_BRANCH }}'
          #       - name: REVISION
          #         value: '{{ workflow.parameters.GIT_REVISION }}'
          #       - name: CONTEXT
          #         value: argo-platform/ci
          #       - name: GITHUB_TOKEN_SECRET
          #         value: github-token
          # - name: submit-security-workflow-no-change-mode
          #   templateRef:
          #     name: codefresh.submit-workflow
          #     template: main
          #   arguments:
          #     parameters:
          #       - name: TEMPLATE_NAME
          #         value: argo-platform-security
          #       - name: ENTRYPOINT
          #         value: main
          #       - name: GIT_REPO
          #         value: '{{ workflow.parameters.GIT_REPO }}'
          #       - name: GIT_BRANCH
          #         value: '{{ workflow.parameters.GIT_BRANCH }}'
          #       - name: GIT_REVISION
          #         value: '{{ workflow.parameters.GIT_REVISION }}'
          #       - name: GIT_REVISION_SHORT
          #         value: '{{ workflow.parameters.GIT_REVISION_SHORT }}'
          #   depends: is-no-change-mode
          #   when: '{{ tasks.is-no-change-mode.outputs.parameters.result }} == true'
          # - name: submit-e2e-workflow-no-change-mode
          #   templateRef:
          #     name: codefresh.submit-workflow
          #     template: main
          #   arguments:
          #     parameters:
          #       - name: TEMPLATE_NAME
          #         value: argo-platform-e2e
          #       - name: ENTRYPOINT
          #         value: main
          #       - name: GIT_REPO
          #         value: '{{ workflow.parameters.GIT_REPO }}'
          #       - name: GIT_BRANCH
          #         value: '{{ workflow.parameters.GIT_BRANCH }}'
          #       - name: GIT_REVISION
          #         value: '{{ workflow.parameters.GIT_REVISION }}'
          #       - name: GIT_REVISION_SHORT
          #         value: '{{ workflow.parameters.GIT_REVISION_SHORT }}'
          #   depends: is-no-change-mode
          #   when: '{{ tasks.is-no-change-mode.outputs.parameters.result }} == true'
          # - name: terminate-previous-builds
          #   templateRef:
          #     name: codefresh.terminate-workflow
          #     template: main
          #   arguments:
          #     parameters:
          #       - name: LABEL_SELECTOR
          #         value: >-
          #           git-branch={{ workflow.labels.git-branch
          #           }},workflow-template-name=argo-platform-ci
          #       - name: FIELD_SELECTOR
          #         value: metadata.name!={{ workflow.name }}
          #   depends: is-no-change-mode
          #   when: '{{ tasks.is-no-change-mode.outputs.parameters.result }} != true'
          - name: repo
            templateRef:
              name: git
              template: clone
            arguments:
              parameters:
                - name: REPO
                  value: '{{ workflow.parameters.GIT_REPO }}'
                - name: REVISION
                  value: '{{ workflow.parameters.GIT_REVISION }}'
                - name: GIT_TOKEN_SECRET
                  value: github-token
            # depends: is-no-change-mode
            # when: '{{ tasks.is-no-change-mode.outputs.parameters.result }} != true'
          # - name: create-pull-request
          #   templateRef:
          #     name: codefresh.github-create-pr
          #     template: main
          #   arguments:
          #     artifacts:
          #       - name: repo
          #         from: '{{ tasks.repo.outputs.artifacts.repo }}'
          #     parameters:
          #       - name: BRANCH
          #         value: '{{ workflow.parameters.GIT_BRANCH }}'
          #       - name: MESSAGE
          #         value: '{{ workflow.parameters.GIT_BRANCH }}'
          #       - name: PR_TEMPLATE
          #         value: >-
          #           https://raw.githubusercontent.com/ariel-codefresh/template/main/pr
          #       - name: GITHUB_TOKEN_SECRET
          #         value: github-token
          #   depends: repo.Succeeded
          # - name: runtime-version
          #   templateRef:
          #     name: util
          #     template: get-runtime-version
          #   arguments:
          #     artifacts:
          #       - name: repo
          #         from: '{{ tasks.repo.outputs.artifacts.repo }}'
          #   depends: repo.Succeeded
          # - name: app-list
          #   templateRef:
          #     name: util
          #     template: get-app-list
          #   arguments:
          #     artifacts:
          #       - name: repo
          #         from: '{{ tasks.repo.outputs.artifacts.repo }}'
          #   depends: repo.Succeeded
          # - name: service-version
          #   templateRef:
          #     name: util
          #     template: get-service-version
          #   arguments:
          #     artifacts:
          #       - name: repo
          #         from: '{{ tasks.repo.outputs.artifacts.repo }}'
          #   depends: repo.Succeeded
          # - name: artifact-version
          #   templateRef:
          #     name: util
          #     template: print-message
          #   arguments:
          #     parameters:
          #       - name: MESSAGE
          #         value: >-
          #           {{ tasks.service-version.outputs.result }}-{{
          #           workflow.parameters.GIT_BRANCH }}-{{
          #           workflow.parameters.GIT_REVISION_SHORT }}




          #   depends: service-version.Succeeded
          # - name: build-images
          #   templateRef:
          #     name: kaniko
          #     template: build
          #   arguments:
          #     artifacts:
          #       - name: repo
          #         from: '{{ tasks.repo.outputs.artifacts.repo }}'
          #     parameters:
          #       - name: BRANCH_IMAGE
          #         value: >-
          #           gcr.io/codefresh-sa/salesdemocf/buslog:{{ workflow.parameters.GIT_BRANCH }}-{{ workflow.parameters.GIT_REVISION_SHORT }}
          #       - name: PERMANENT_IMAGE
          #         value: >-
          #           gcr.io/codefresh-sa/salesdemocf/buslog:latest
          #       - name: DOCKERFILE
          #         # value: apps/{{ item }}/Dockerfile
          #         value: buslog/Dockerfile
          #       - name: APP
          #         # value: '{{ item }}'
          #         value: buslog
          #       - name: GIT_BRANCH
          #         value: '{{ workflow.parameters.GIT_BRANCH }}'
          #       - name: GIT_REPO_OWNER
          #         value: '{{ workflow.parameters.GIT_REPO_OWNER }}'
          #       - name: GIT_REPO_NAME
          #         value: '{{ workflow.parameters.GIT_REPO_NAME }}'
          #       - name: GIT_REVISION
          #         value: '{{ workflow.parameters.GIT_REVISION }}'
          #       - name: GIT_COMMIT_MESSAGE
          #         value: '{{ workflow.parameters.GIT_COMMIT_MESSAGE }}'
          #       - name: GIT_COMMIT_URL
          #         value: '{{ workflow.parameters.GIT_COMMIT_URL }}'
          #   # depends: app-list && artifact-version
          #   # withParam: '{{ tasks.app-list.outputs.result }}'




    #       - name: report-images-revision
    #         templateRef:
    #           name: common-util
    #           template: report-image
    #         arguments:
    #           parameters:
    #             - name: IMAGE_URI
    #               value: >-
    #                 gcr.io/codefresh-inc/codefresh-io/argo-platform-{{ item
    #                 }}:{{ tasks.artifact-version.outputs.result }}
    #             - name: CF_API_KEY_SECRET
    #               value: codefresh-v1-api-token
    #         depends: build-images
    #         withParam: '{{ tasks.app-list.outputs.result }}'
    #       - name: report-images-branch
    #         templateRef:
    #           name: common-util
    #           template: report-image
    #         arguments:
    #           parameters:
    #             - name: IMAGE_URI
    #               value: >-
    #                 gcr.io/codefresh-inc/codefresh-io/argo-platform-{{ item
    #                 }}:{{ workflow.parameters.GIT_BRANCH }}
    #             - name: CF_API_KEY_SECRET
    #               value: codefresh-v1-api-token
    #         depends: report-images-revision
    #         withParam: '{{ tasks.app-list.outputs.result }}'
    #       - name: submit-security-workflow
    #         templateRef:
    #           name: codefresh.submit-workflow
    #           template: main
    #         arguments:
    #           parameters:
    #             - name: TEMPLATE_NAME
    #               value: argo-platform-security
    #             - name: ENTRYPOINT
    #               value: main
    #             - name: GIT_REPO
    #               value: '{{ workflow.parameters.GIT_REPO }}'
    #             - name: GIT_BRANCH
    #               value: '{{ workflow.parameters.GIT_BRANCH }}'
    #             - name: GIT_REVISION
    #               value: '{{ workflow.parameters.GIT_REVISION }}'
    #             - name: GIT_REVISION_SHORT
    #               value: '{{ workflow.parameters.GIT_REVISION_SHORT }}'
    #         depends: build-images
    #       - name: submit-e2e-workflow
    #         templateRef:
    #           name: codefresh.submit-workflow
    #           template: main
    #         arguments:
    #           parameters:
    #             - name: TEMPLATE_NAME
    #               value: argo-platform-e2e
    #             - name: ENTRYPOINT
    #               value: main
    #             - name: GIT_REPO
    #               value: '{{ workflow.parameters.GIT_REPO }}'
    #             - name: GIT_BRANCH
    #               value: '{{ workflow.parameters.GIT_BRANCH }}'
    #             - name: GIT_REVISION
    #               value: '{{ workflow.parameters.GIT_REVISION }}'
    #             - name: GIT_REVISION_SHORT
    #               value: '{{ workflow.parameters.GIT_REVISION_SHORT }}'
    #         depends: build-images
    #       - name: unit-tests
    #         templateRef:
    #           name: testing
    #           template: unit-tests
    #         arguments:
    #           parameters:
    #             - name: RUNTIME_VERSION
    #               value: '{{ tasks.runtime-version.outputs.result }}'
    #           artifacts:
    #             - name: repo
    #               from: '{{ tasks.repo.outputs.artifacts.repo }}'
    #         depends: runtime-version
    #       - name: helm-chart
    #         templateRef:
    #           name: helm
    #           template: publish
    #         arguments:
    #           artifacts:
    #             - name: repo
    #               from: '{{ tasks.repo.outputs.artifacts.repo }}'
    #           parameters:
    #             - name: CHART_PATH
    #               value: .deploy/chart
    #             - name: CHART_VERSION
    #               value: '{{ tasks.artifact-version.outputs.result }}'
    #             - name: CHARTMUSEUM_SECRET
    #               value: chartmuseum-dev-credentials
    #         depends: build-images
    # - name: exit-handler
    #   steps:
    #     - - name: report-commits-status-failure
    #         when: '{{workflow.status}} =~ "Failed|Error"'
    #         templateRef:
    #           name: codefresh.github-commit-status
    #           template: main
    #         arguments:
    #           parameters:
    #             - name: BUILD_BASE_URL
    #               value: >-
    #                 https://inc03.cf-op.com/workflows/workflows/codefresh-v2-production/
    #             - name: REPO_OWNER
    #               value: codefresh-io
    #             - name: REPO_NAME
    #               value: argo-platform
    #             - name: REVISION
    #               value: '{{ workflow.parameters.GIT_REVISION }}'
    #             - name: STATE
    #               value: failure
    #             - name: CONTEXT
    #               value: argo-platform/ci
    #             - name: DESCRIPTION
    #               value: Workflow failed
    #             - name: GITHUB_TOKEN_SECRET
    #               value: github-token
    #     - - name: report-commits-status-success
    #         when: '{{workflow.status}} == Succeeded'
    #         templateRef:
    #           name: codefresh.github-commit-status
    #           template: main
    #         arguments:
    #           parameters:
    #             - name: BUILD_BASE_URL
    #               value: >-
    #                 https://inc03.cf-op.com/workflows/workflows/codefresh-v2-production/
    #             - name: REPO_OWNER
    #               value: codefresh-io
    #             - name: REPO_NAME
    #               value: argo-platform
    #             - name: REVISION
    #               value: '{{ workflow.parameters.GIT_REVISION }}'
    #             - name: STATE
    #               value: success
    #             - name: CONTEXT
    #               value: argo-platform/ci
    #             - name: DESCRIPTION
    #               value: Workflow succeeded
    #             - name: GITHUB_TOKEN_SECRET
    #               value: github-token
